### ISSUE TITLE
Typos and Errors in Functions Run Offline

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/docs#111]
1. The CMD and Powershell examples have an extra double quote at the end
1. The docs reference the old runtime image names

<img width="846" alt="Screen Shot 2021-11-05 at 9 50 04 AM" src="https://user-images.githubusercontent.com/1477010/140547946-1180975c-2d7c-4f17-a187-ed251e9df140.png">

**Comment by varunsaral** [comment]
can i take this?

**Comment by eldadfux** [comment]
@varunsaral yes, you can submit a PR.

**Comment by stnguyen90** [comment]
Closing as this section has been removed.
