### ISSUE TITLE
Enhanced Readme links

### ISSUE THREAD

**Issue by Anubhavdevv** [appwrite/docs#131]
The enhancement in the documentation 
```The official https://appwrite.io/docs documentation source code.```
wrapping link text in brackets [ ]
It would look professional by adding Appwrite Docs and then mention link rather than mentioning whole link 

Please assign this issue to  me

**Comment by Anubhavdevv** [comment]
@eldadfux Please assign this to me

**Comment by stnguyen90** [comment]
@Anubhavdevv, assigned! Thanks for the assistance! 🙏

**Comment by ShyamPraveenSingh** [comment]
Hi, @stnguyen90 @eldadfux is this issue still open?
