### ISSUE TITLE
An example/explanation would be appreciated

### ISSUE THREAD

**Issue by Just-Moh-it** [appwrite/docs#187]
When looking through the docs: https://appwrite.io/docs/database#querying-documents

I was unable to understand what 'separated by commas' meant, since it was unclear as to which coma was being talked of. The example does help, but there's no explanation about it. I had to look through 2-3 projects that I suspected had this functionality where I would be able to distinguish a logical or and an and. 

It would be greatly appreciated if such a vital part of the application docs were absolutely clear. Thanks

**Comment by saigoud25** [comment]
can I work on this and change the doc?

**Comment by stnguyen90** [comment]
@Just-Moh-it, the example now shows this:

<img width="839" alt="image" src="https://user-images.githubusercontent.com/1477010/192635741-78892d8c-1f93-4996-bc18-8cdf6042f9b2.png">

Can this be closed now?

**Comment by Just-Moh-it** [comment]
Yep, added in #247! So, closing this now 🥳
