### ISSUE TITLE
📚 Documentation: Translation - Nepali

### ISSUE THREAD

**Issue by srishtipoudel** [appwrite/docs#284]
### 💭 Description

I want to contribute by translating the docs into Nepali Language. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by aadii0408** [comment]
hi, can you please assign this to me? Also, I will be grateful to you if you tag this as my Hacktoberfest 2022 contribution.

**Comment by stnguyen90** [comment]
@srishtipoudel Thanks for raising this issue! 🙏 Unfortunately, this is not something we want to move forward at the moment as it would be difficult for us to maintain. We'll be sure to revisit this in the future when appropriate. For now, I'm going to close this as it seems to track a lot of interest in contribution.
