### ISSUE TITLE
Want to Add Contributing.md and modify README with hacktoberfest specific

### ISSUE THREAD

**Issue by Rancho2002** [appwrite/docs#292]
### 💭 Description

As contributing.md is necessary for a valid repo in hacktoberfest, I want to add this in this repository. Please assign it to me. @brandonroberts 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Rancho2002 Thanks for raising this issue, but we are not interested in adding a contributing.md to this repo. The README serves as contributing documentation. If you're looking to contribute please try exploring hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/). If you have any problems or need help, please join our [Discord community](https://appwrite.io/discord) and use the `#hacktoberfest` channel.
