### ISSUE TITLE
🚀 Feature: Adding Hover Effect to Social Icons

### ISSUE THREAD

**Issue by Kritika30032002** [appwrite/docs#294]
### 🔖 Feature description

 Adding Hover Effect to Social Icons and links if available.
 
 Assign this to me!!

### 🎤 Pitch

Adding Hover Effect helps us to understand that which icon s selected when we hover on them.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Kritika30032002 thanks for raising this issue! 🙏 Unfortunately, it's difficult to contribute something like this as the source code for this is not public. We'll keep it in mind moving forward, though! For now, I'm going to close this so it doesn't attract extra attention, especially during Hacktoberfest.

If you'd like to contribute to Appwrite, try exploring hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/). If you have any problems or need help, please join our [Discord community](https://appwrite.io/discord) and use the `#hacktoberfest` channel.
