### ISSUE TITLE
Anchor links scroll behind the sticky actions bar

### ISSUE THREAD

**Issue by alexweininger** [appwrite/docs#30]
## Issue

Repro:

1. Go to https://appwrite.io/docs/server/storage
2. Click an anchor link (e.g. from this list)

<img width="180" alt="Screen Shot 2021-06-04 at 2 33 38 PM" src="https://user-images.githubusercontent.com/12476526/120864918-e5918f00-c541-11eb-96e1-02775c5a58dc.png">

Actual:
Sticky header covers the title.
<img width="841" alt="Screen Shot 2021-06-04 at 2 32 11 PM" src="https://user-images.githubusercontent.com/12476526/120864815-b0853c80-c541-11eb-89ed-5de2c67723af.png">

Expected:
Sticky header should not cover title.
<img width="518" alt="Screen Shot 2021-06-04 at 2 32 23 PM" src="https://user-images.githubusercontent.com/12476526/120864836-b8dd7780-c541-11eb-80ca-2bf44ecd451d.png">

## Fix

This can easily be fixed with the `scroll-margin-top` CSS property. Just add it to all the anchors with a value equal to the actions bar height which seems to be `74px`.

<img width="407" alt="Screen Shot 2021-06-04 at 2 36 12 PM" src="https://user-images.githubusercontent.com/12476526/120865112-3ef9be00-c542-11eb-8e8b-f77a2f0c4a25.png">

More info on `scroll-margin-top` and how to use it:
https://gomakethings.com/how-to-prevent-anchor-links-from-scrolling-behind-a-sticky-header-with-one-line-of-css/

I'd like to fix this but I'm not sure where the styling is located, or if I can do it all inline. I also would have to verify how this effects mobile layouts and the other responsive layouts.

**Comment by eldadfux** [comment]
Now available on https://appwrite.io/docs - thanks for the suggestion @alexweininger !
