### ISSUE TITLE
📚 Documentation: Document `_APP_SMS_PROVIDER` for various Providers

### ISSUE THREAD

**Issue by mikeamir** [appwrite/docs#301]
### 💭 Description

The phone authentication needs to be more clear when it comes to integrating SMS providers because some SMS providers are integrated with different credentials than the ones mentioned in the documentation

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@gewenyu99, where do you think we should document this?

**Comment by gewenyu99** [comment]
> @gewenyu99, where do you think we should document this?

This is actually documented in environment variables. We only accept a select set of providers (I think we support 3).

I wonder if we can make it clearer in both API docs and Auth guide that we only support a few providers.

**Comment by stnguyen90** [comment]
@gewenyu99,

The docs say `_APP_SMS_PROVIDER` should be `sms://[USER]:[SECRET]@[PROVIDER]`, but what is `[USER]` and `[SECRET]` for each provider? The docs say `_APP_SMS_FROM` should be a phone number, but that's actually not the case for some providers. For example, Msg91 requires:

> `_APP_SMS_PROVIDER` value should be in format as `phone://[senderID]:[authKey]@MSG91`
> `_APP_SMS_FROM` value should be flow ID created in Msg91

**Comment by gewenyu99** [comment]
@stnguyen90 Do you feel this is a problem that applies to other types of providers, too?

Maybe what we need is a "providers" page. Another option is to add a table under the Authentication guide.

WDYT

**Comment by stnguyen90** [comment]
@gewenyu99 it does with 360 dialog (Whatsapp) too. Ya, under authentication might be good.

**Comment by yashdev9274** [comment]
Hey @stnguyen90 is this issue still is process, is there anything i can help with .

**Comment by stnguyen90** [comment]
@yashdev9274 this might be best for the core team to figure out the best way to document this. If you're interested in contributing, keep an eye out for issues labeled "good first issue"

**Comment by gewenyu99** [comment]
@stnguyen90 We can do it in this PR
https://github.com/appwrite/docs/pull/312

I'll add it here and get your review
