### ISSUE TITLE
🐛 Bug Report: Svelte example todo app doesn't work as expected

### ISSUE THREAD

**Issue by beingflo** [appwrite/docs#307]
### 👟 Reproduction steps

- Visit the Svelte example app https://appwrite-todo-with-svelte.vercel.app/#/ as linked here https://appwrite.io/docs/getting-started-for-web.
- Sign up
- Try adding an item

### 👍 Expected behavior

Should get added as in the React example deployment

### 👎 Actual Behavior

API throws 401 (invisible to the user unless console is opened)

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Thanks for raising this issue! 🙏🏼 This is probably because the todo is outdated and is pending an update (https://github.com/appwrite/demo-todo-with-svelte/pull/44).
