### ISSUE TITLE
Make environment variable category headers anchor links just like service docs

### ISSUE THREAD

**Issue by alexweininger** [appwrite/docs#31]
Service doc pages have headers for things with anchor links:
<img width="309" alt="Screen Shot 2021-06-04 at 2 40 03 PM" src="https://user-images.githubusercontent.com/12476526/120865433-e70f8700-c542-11eb-83fa-dbbb951a8cc9.png">

The env vars page has anchors but not links:
<img width="270" alt="Screen Shot 2021-06-04 at 2 40 22 PM" src="https://user-images.githubusercontent.com/12476526/120865429-e5de5a00-c542-11eb-942b-10446981a10e.png">

Should be a simple addition.

Markup for env var category headers:

```html
 <h2 id="<?php echo $this->escape(strtolower(str_replace(' ', '_', $category))); ?>"><?php echo $this->escape($category); ?></h2>
```

Markup for service header links:
```html
<h2 class="margin-bottom">
    <a href="/docs/<?php echo $this->escape($family); ?>/<?php echo $serviceName; ?>#<?php echo $operation['operationId']; ?>" id="<?php echo $operation['operationId']; ?>"><?php echo $this->escape($title); ?></a>
</h2>
```

**Comment by eldadfux** [comment]
Done in #34

**Comment by eldadfux** [comment]
Now available on https://appwrite.io/docs
