### ISSUE TITLE
Upgrade our issue templates to use GitHub issue forms ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/docs#64]
# Introduction

GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

Appwrite currently uses the older [issue template format](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). Your task is to create **GitHub issue forms** for this repository. Please use [Appwrite's issue templates](https://github.com/appwrite/appwrite/tree/master/.github/ISSUE_TEMPLATE) as a reference for this PR.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Prepare **bug report** issue form in `.github/ISSUE_TEMPLATE/bug.yaml`
- [ ] Prepare **documentation** issue form in `.github/ISSUE_TEMPLATE/documentation.yaml`
- [ ] Prepare **feature request** issue form in `.github/ISSUE_TEMPLATE/feature.yaml`
- [ ] Push changes to **master** and test issue forms on your fork
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by EugeneGohh** [comment]
Hi @Meldiron, can I work on this?

**Comment by vj-codes** [comment]
@Meldiron hey I have created a PR, please add the hacktoberfest-accepted label and hacktoberfest topic to this repository as well.
Thankss in advance:)

**Comment by Vidushi-Gupta** [comment]
Hi! I hope the assignments for Hacktoberfest have begun. Could you please assign it to me for the hacktoberfest?

**Comment by bipinparajuli** [comment]
hey, team can you please assign it to me?

**Comment by vj-codes** [comment]
Do review my PR #66 , thankss in advance :)

**Comment by christyjacob4** [comment]
@EugeneGohh All the best :rocket:

**Comment by christyjacob4** [comment]
@vj-codes  @Vidushi-Gupta @bipinparajuli  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by EugeneGohh** [comment]
This issue is related to PR #70 .

**Comment by EugeneGohh** [comment]
It said this project is not participating in my Hacktoberfest profile but this issue label Hacktoberfest. Can you please put a topic label "Hacktoberfest" for this repo? Thanks.

**Comment by Meldiron** [comment]
@EugeneGohh Thanks for the PR! 🤯 Please give us some time to review it.

Hmm, that is weird, I will take to the team about this problem. Thanks for letting us know.

**Comment by Meldiron** [comment]
@EugeneGohh We added `hacktoberfest` topic to all of our repositories. Thanks for letting us know about this issue ❤️

**Comment by christina-izquierdo** [comment]
Hi there this is my first hacktoberfest and contribution to open source. Are we still able to work on this issue? Thanks!

**Comment by christyjacob4** [comment]
@EugeneGohh  Let us know if you're not working on this . We will need to reassign in

**Comment by EugeneGohh** [comment]
> @EugeneGohh Let us know if you're not working on this . We will need to reassign in

Refer to #71 . No updates and decided to close for good.

**Comment by loftwah** [comment]
That looks like it is a fix I think.

**Comment by aniketh-varma** [comment]
@christyjacob4 @Meldiron I can help with this issue if it's still open.

**Comment by stnguyen90** [comment]
@Meldiron, can we close this since we have the default template in the [org repo now](https://github.com/appwrite/.github/tree/main/.github/ISSUE_TEMPLATE)?
