### ISSUE TITLE
Remove `--save` flag when installing Appwrite SDK in Ruby

### ISSUE THREAD

**Issue by oliver-pham** [appwrite/docs#82]
The docs suggest that  `--save` should be included when installing Appwrite SDK in Ruby. However, `gem` doesn't support that option.

![Screen Shot 2021-10-06 at 10 47 58 PM](https://user-images.githubusercontent.com/55090719/136312257-729f2d16-3593-4866-8691-162e26c3d6b6.jpg)

**Comment by Ln11211** [comment]
@oliver-pham , where exactly is the file located ?, can you please tell me the file name ?
